isstatic: true
name: test
provider: amazon
source:
regions:
  -
    name: region-1
    id: region-id-1
    data:
      zones:
        strategy: exact
        data:
          - zone-a
          - zone-b
          - zone-c
      images:
        strategy: exact
        data:
          -
            name: img-1
            gpuavailable: false
            version: img-version
          -
            name: img-2
            gpuavailable: false
            version: img-version
      versions:
        strategy: exact
        data:
          - version-1
          - version-2
      vms:
        strategy: exact
        data:
          -
            Type: xlarge
            Cpus: 4
            Gpus: 0
            Mem: 16
            NtwPerf:
            NtwPerfCat:
            OnDemandPrice: 0.5
            Zones:
              -
            Attributes:
              -
  -
    name: region-2
    id: region-id-2