kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "cloudinfo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    helm.sh/chart: {{ include "cloudinfo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
    log:
      level: {{ .Values.app.logLevel }}
    metrics:
      enabled: {{ .Values.metrics.enabled }}
  oci.properties: |-
    [DEFAULT]
    user={{ .Values.providers.oracle.ociUser }}
    tenancy={{ .Values.providers.oracle.ociTenancy }}
    region={{ .Values.providers.oracle.ociRegion }}
    fingerprint={{ .Values.providers.oracle.ociFingerprint }}
    key_file=/etc/cloudinfo/credentials/oci_key.pem
