apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudinfo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    helm.sh/chart: {{ include "cloudinfo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
    {{- end }}
  annotations:
{{ toYaml .Values.deploymentAnnotations | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["cloudinfo", "--listen-address=0.0.0.0:8000", "--metrics-address=0.0.0.0:{{ .Values.metrics.port }}"]
          volumeMounts:
            - name: credentials
              mountPath: /etc/cloudinfo/credentials
              readOnly: true
            - name: config
              mountPath: /etc/cloudinfo/config
              readOnly: true
          env:
            - name: CLOUDINFO_BASEPATH
              value: {{ .Values.app.basePath }}
            - name: CLOUDINFO_CONFIG_DIR
              value: /etc/cloudinfo/config
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/cloudinfo/credentials/google.json
            - name: AZURE_AUTH_LOCATION
              value: /etc/cloudinfo/credentials/azure.json
            - name: ORACLE_CLI_CONFIG_LOCATION
              value: /etc/cloudinfo/config/oci.properties
          envFrom:
            - secretRef:
                name: {{ template "cloudinfo.fullname" . }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.basePath }}/status
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.app.basePath }}/status
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: credentials
          secret:
            secretName: {{ template "cloudinfo.fullname" . }}-credentials
        - name: config
          configMap:
            name: "{{ template "cloudinfo.fullname" . }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
