apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudinfo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    helm.sh/chart: {{ include "cloudinfo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.providers.amazon.enabled }}
  CLOUDINFO_PROVIDER_AMAZON_ENABLED: {{ print "true" | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.providers.amazon.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.providers.amazon.awsSecretAccessKey | b64enc | quote }}
  {{ end }}
  {{ if .Values.providers.google.enabled }}
  CLOUDINFO_PROVIDER_GOOGLE_ENABLED: {{ print "true" | b64enc | quote }}
  GCE_API_KEY: {{ .Values.providers.google.gceApiKey | b64enc | quote }}
  {{ end }}
  {{ if .Values.providers.alibaba.enabled }}
  CLOUDINFO_PROVIDER_ALIBABA_ENABLED: {{ print "true" | b64enc | quote }}
  ALIBABA_ACCESS_KEY_ID: {{ .Values.providers.alibaba.alibabaAccessKeyId | b64enc | quote }}
  ALIBABA_ACCESS_KEY_SECRET: {{ .Values.providers.alibaba.alibabaAccessKeySecret | b64enc | quote }}
  ALIBABA_REGION_ID: {{ .Values.providers.alibaba.alibabaRegionId | b64enc | quote }}
  {{ end }}
  {{ if .Values.providers.oracle.enabled }}
  CLOUDINFO_PROVIDER_ORACLE_ENABLED: {{ print "true" | b64enc | quote }}
  {{ end }}
  {{ if .Values.providers.azure.enabled }}
  CLOUDINFO_PROVIDER_AZURE_ENABLED: {{ print "true" | b64enc | quote }}
  {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudinfo.fullname" . }}-credentials
  labels:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    helm.sh/chart: {{ include "cloudinfo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.providers.google.enabled }}
  google.json: {{ .Values.providers.google.gceCredentials | quote }}
  {{ end }}
  {{ if .Values.providers.azure.enabled }}
  azure.json: {{ .Values.providers.azure.azureCredentials | quote }}
  {{ end }}
  {{ if .Values.providers.oracle.enabled }}
  oci_key.pem: {{ .Values.providers.oracle.ociKey | quote }}
  {{ end }}
